services:
  db:
    image: postgres:16
    container_name: smartserve-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - smartserve-network

  odoo:
    image: odoo:18
    container_name: smartserve-odoo
    restart: always
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    environment:
      HOST: db
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../config/odoo.conf:/etc/odoo/odoo.conf
      - ../custom_addons:/mnt/extra-addons
      - ../data/odoo:/var/lib/odoo
    networks:
      - smartserve-network

networks:
  smartserve-network:
    driver: bridge
    